services:
  postgres:
    image: postgres:13
    container_name: hotel_booking_postgres
    environment:
      POSTGRES_DB: hotel_booking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
