version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hotel_booking_postgres
    environment:
      POSTGRES_DB: hotel_booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hotel_booking_network

  app:
    build: .
    container_name: hotel_booking_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotel_booking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - hotel_booking_network

volumes:
  postgres_data:

networks:
  hotel_booking_network:
    driver: bridge